// Coverage: render docs/coverage.md from the case table.
//
// Deterministic by construction: buildCases is pure, so it is called with a placeholder fixture
// of constant strings (no filesystem access, no real symlinks), and only stable fields are
// rendered in buildCases order. coverage.ts must NOT sort — CI's `git diff --exit-code` is meant
// to catch a reorder, an addition, or a removal, and sorting would hide the first two.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildCases, PLACEHOLDER_FIXTURE } from "../probe/cases.ts";

function escapeCell(s: string): string {
	return s.replace(/\|/g, "\\|").replace(/\n/g, "\\n");
}

function main(): void {
	const cases = buildCases(PLACEHOLDER_FIXTURE);
	const lines: string[] = [];
	lines.push("# Probe coverage");
	lines.push("");
	lines.push("Generated by `bun run coverage` from `probe/cases.ts`. **Do not edit by hand.**");
	lines.push("CI runs `bun run coverage && git diff --exit-code docs/coverage.md`, so this file");
	lines.push("must be regenerated whenever the case table changes.");
	lines.push("");
	lines.push(`Total cases: ${cases.length}.`);
	lines.push("");
	lines.push("| family | label | tool | layer | ruleId | reasonIncludes | deliberate | known | item/ref |");
	lines.push("|---|---|---|---|---|---|---|---|---|");
	for (const c of cases) {
		const tag = c.item !== undefined ? `item=${c.item}` : c.ref !== undefined ? `ref=${c.ref}` : "";
		lines.push(
			`| ${escapeCell(c.family)} | ${escapeCell(c.label)} | ${escapeCell(c.tool)} | ${c.expected.layer} | ` +
				`${escapeCell(c.expected.ruleId ?? "")} | ${escapeCell(c.expected.reasonIncludes ?? "")} | ` +
				`${escapeCell(c.expected.deliberate ?? "")} | ${c.expected.known ?? ""} | ${escapeCell(tag)} |`,
		);
	}
	lines.push("");

	const out = path.join(path.dirname(path.dirname(fileURLToPath(import.meta.url))), "docs", "coverage.md");
	fs.writeFileSync(out, `${lines.join("\n")}\n`);
	console.log(`coverage: wrote ${out} (${cases.length} cases)`);
}

main();
